version: "3.8"
services:
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - basketdb_volume:/data/db
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQUrl=rabbitmq
      - MongoDbSettings:ConnectionString=mongodb://basketdb:27017
    ports:
      - "5001:80"
    depends_on:
      - basketdb
  gateway.api:
    container_name: gateway.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"
  elasticsearch:
    container_name: elasticsearch
    volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        - elkdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ELASTIC_PASSWORD: "elastic"
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      discovery.type: single-node
  kibana:
    container_name: kibana
    volumes:
        - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

